project_id = "oxcxqjubctslypthviux"

[functions.analyze-prescription]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:3000"
additional_redirect_urls = ["https://oxcxqjubctslypthviux.supabase.co"]

[edge_functions]
enabled = true
port = 54321

[functions.paddle-webhook]
verify_jwt = false